namespace NWN.Enums
{
    // These are for GetFirstInPersistentObject() and GetNextInPersistentObject()
    public enum Animation
    {
        // Looping animation constants.
        LOOPING_PAUSE = 0,
        LOOPING_PAUSE2 = 1,
        LOOPING_LISTEN = 2,
        LOOPING_MEDITATE = 3,
        LOOPING_WORSHIP = 4,
        LOOPING_LOOK_FAR = 5,
        LOOPING_SIT_CHAIR = 6,
        LOOPING_SIT_CROSS = 7,
        LOOPING_TALK_NORMAL = 8,
        LOOPING_TALK_PLEADING = 9,
        LOOPING_TALK_FORCEFUL = 10,
        LOOPING_TALK_LAUGHING = 11,
        LOOPING_GET_LOW = 12,
        LOOPING_GET_MID = 13,
        LOOPING_PAUSE_TIRED = 14,
        LOOPING_PAUSE_DRUNK = 15,
        LOOPING_DEAD_FRONT = 16,
        LOOPING_DEAD_BACK = 17,
        LOOPING_CONJURE1 = 18,
        LOOPING_CONJURE2 = 19,
        LOOPING_SPASM = 20,
        LOOPING_CUSTOM1 = 21,
        LOOPING_CUSTOM2 = 22,
        LOOPING_CUSTOM3 = 23,
        LOOPING_CUSTOM4 = 24,
        LOOPING_CUSTOM5 = 25,
        LOOPING_CUSTOM6 = 26,
        LOOPING_CUSTOM7 = 27,
        LOOPING_CUSTOM8 = 28,
        LOOPING_CUSTOM9 = 29,
        LOOPING_CUSTOM10 = 30,
        LOOPING_CUSTOM11 = 31,
        LOOPING_CUSTOM12 = 32,
        LOOPING_CUSTOM13 = 33,
        LOOPING_CUSTOM14 = 34,
        LOOPING_CUSTOM15 = 35,
        LOOPING_CUSTOM16 = 36,
        LOOPING_CUSTOM17 = 37,
        LOOPING_CUSTOM18 = 38,
        LOOPING_CUSTOM19 = 39,
        LOOPING_CUSTOM20 = 40,
        MOUNT1 = 41,
        DISMOUNT1 = 42,

        // Fire and forget animation constants.
        FIREFORGET_HEAD_TURN_LEFT = 100,
        FIREFORGET_HEAD_TURN_RIGHT = 101,
        FIREFORGET_PAUSE_SCRATCH_HEAD = 102,
        FIREFORGET_PAUSE_BORED = 103,
        FIREFORGET_SALUTE = 104,
        FIREFORGET_BOW = 105,
        FIREFORGET_STEAL = 106,
        FIREFORGET_GREETING = 107,
        FIREFORGET_TAUNT = 108,
        FIREFORGET_VICTORY1 = 109,
        FIREFORGET_VICTORY2 = 110,
        FIREFORGET_VICTORY3 = 111,
        FIREFORGET_READ = 112,
        FIREFORGET_DRINK = 113,
        FIREFORGET_DODGE_SIDE = 114,
        FIREFORGET_DODGE_DUCK = 115,
        FIREFORGET_SPASM = 116,

        // Placeable animation constants
        PLACEABLE_ACTIVATE = 200,
        PLACEABLE_DEACTIVATE = 201,
        PLACEABLE_OPEN = 202,
        PLACEABLE_CLOSE = 203,

        // Door animation constants
        DOOR_CLOSE = 204,
        DOOR_OPEN1 = 205,
        DOOR_OPEN2 = 206,
        DOOR_DESTROY = 207
    }
}