namespace NWN.Enums
{
    public enum IpConstFeat
    {
        ALERTNESS = 0,
        AMBIDEXTROUS = 1,
        CLEAVE = 2,
        COMBAT_CASTING = 3,
        DODGE = 4,
        EXTRA_TURNING = 5,
        KNOCKDOWN = 6,
        POINTBLANK = 7,
        SPELLFOCUSABJ = 8,
        SPELLFOCUSCON = 9,
        SPELLFOCUSDIV = 10,
        SPELLFOCUSENC = 11,
        SPELLFOCUSEVO = 12,
        SPELLFOCUSILL = 13,
        SPELLFOCUSNEC = 14,
        SPELLPENETRATION = 15,
        POWERATTACK = 16,
        TWO_WEAPON_FIGHTING = 17,
        WEAPSPEUNARM = 18,
        WEAPFINESSE = 19,
        IMPCRITUNARM = 20,
        WEAPON_PROF_EXOTIC = 21,
        WEAPON_PROF_MARTIAL = 22,
        WEAPON_PROF_SIMPLE = 23,
        ARMOR_PROF_HEAVY = 24,
        ARMOR_PROF_LIGHT = 25,
        ARMOR_PROF_MEDIUM = 26,
        MOBILITY = 27,
        DISARM = 28,
        WHIRLWIND = 29,
        RAPID_SHOT = 30,
        HIDE_IN_PLAIN_SIGHT = 31,
        SNEAK_ATTACK_1D6 = 32,
        SNEAK_ATTACK_2D6 = 33,
        SNEAK_ATTACK_3D6 = 34,
        SHIELD_PROFICIENCY = 35,
        USE_POISON = 36,
        DISARM_WHIP = 37,
        WEAPON_PROF_CREATURE = 38,
        SNEAK_ATTACK_5D6 = 39,
        PLAYER_TOOL_01 = 53,
        PLAYER_TOOL_02 = 54,
        PLAYER_TOOL_03 = 55,
        PLAYER_TOOL_04 = 56,
        PLAYER_TOOL_05 = 57,
        PLAYER_TOOL_06 = 58,
        PLAYER_TOOL_07 = 59,
        PLAYER_TOOL_08 = 60,
        PLAYER_TOOL_09 = 61,
        PLAYER_TOOL_10 = 62
    }
}